<p>Name:- Krishna Mundada<p>
<p>Roll No:- 45 </p>
<p>Batch:- E3</p>
<p>Practical 3</p>
<p>Topic:- AutoEncoders </p>
<hr>
<hr>

Implement autoencoder for both binary and real valued input. clearly show the loss after each iteration <br>
number of inputs = 5 <br>
hidden layer = 4 <br>
binary cross entropy loss function and sigmoid activation function<br> 
input = 1 0 1 1 1 <br>

# Binary input

In [53]:
import numpy as np
def sigmoid(x):
    return 1.0 / (1.0 + np.exp(-x))

def sigmoid_derivative(x):
    return sigmoid(x) * (1 - sigmoid(x))

def binary_cross_entropy(y_true, y_pred):
    return -np.mean(y_true * np.log(y_pred) + (1 - y_true) * np.log(1 - y_pred)) 

def binary_cross_entropy_derivative(y_true, y_pred):
    return -(y_true / y_pred) + (1 - y_true) / (1 - y_pred)

# input 
X = np.array([[1, 0, 1, 1, 1]])


input_size = X.shape[1]
hidden_size = 4
output_size = input_size

np.random.seed(0)
W1 = np.random.rand(input_size, hidden_size)
W2 = np.random.rand(hidden_size, output_size)

print(W1)
print(W2)

#  number of epochs and learning rate
epochs = 1000
learning_rate = 0.01


for i in range(epochs):
    # forward pass
    hidden_layer = sigmoid(np.dot(X, W1))
    output_layer = sigmoid(np.dot(hidden_layer, W2))
    # loss 
    loss = binary_cross_entropy(X, output_layer)
    print(f"Epoch {i}, Loss: {loss}")
    # backpropagation
    d_output = binary_cross_entropy_derivative(X, output_layer) * sigmoid_derivative(output_layer)
    d_hidden = np.dot(d_output, W2.T) * sigmoid_derivative(hidden_layer)
    # update weights
    W2 -= learning_rate * np.dot(hidden_layer.T, d_output)
    W1 -= learning_rate * np.dot(X.T, d_hidden)
# output 
reconstructed = sigmoid(np.dot(sigmoid(np.dot(X, W1)), W2))
print()
print("W1: \n",W1)
print("W2: \n",W2)

print("\n\nActual input:", X)
print("Reconstructed input:", reconstructed)


[[0.5488135  0.71518937 0.60276338 0.54488318]
 [0.4236548  0.64589411 0.43758721 0.891773  ]
 [0.96366276 0.38344152 0.79172504 0.52889492]
 [0.56804456 0.92559664 0.07103606 0.0871293 ]
 [0.0202184  0.83261985 0.77815675 0.87001215]]
[[0.97861834 0.79915856 0.46147936 0.78052918 0.11827443]
 [0.63992102 0.14335329 0.94466892 0.52184832 0.41466194]
 [0.26455561 0.77423369 0.45615033 0.56843395 0.0187898 ]
 [0.6176355  0.61209572 0.616934   0.94374808 0.6818203 ]]
Epoch 0, Loss: 0.5525409875705336
Epoch 1, Loss: 0.5405896402642598
Epoch 2, Loss: 0.5293198316123255
Epoch 3, Loss: 0.518654796734852
Epoch 4, Loss: 0.5085302620517479
Epoch 5, Loss: 0.4988918610001586
Epoch 6, Loss: 0.4896931876021272
Epoch 7, Loss: 0.4808943073026781
Epoch 8, Loss: 0.47246060159671205
Epoch 9, Loss: 0.46436186027885984
Epoch 10, Loss: 0.456571560087273
Epoch 11, Loss: 0.44906628551360867
Epoch 12, Loss: 0.4418252593539429
Epoch 13, Loss: 0.4348299589043215
Epoch 14, Loss: 0.4280637996710787
Epoch 15, Loss:

Epoch 364, Loss: 0.01252226176072654
Epoch 365, Loss: 0.012405855849044913
Epoch 366, Loss: 0.012290557810065331
Epoch 367, Loss: 0.012176356912766143
Epoch 368, Loss: 0.012063242530702298
Epoch 369, Loss: 0.011951204140991538
Epoch 370, Loss: 0.01184023132331026
Epoch 371, Loss: 0.011730313758898808
Epoch 372, Loss: 0.011621441229577246
Epoch 373, Loss: 0.01151360361676991
Epoch 374, Loss: 0.011406790900539815
Epoch 375, Loss: 0.011300993158632958
Epoch 376, Loss: 0.011196200565530539
Epoch 377, Loss: 0.011092403391512231
Epoch 378, Loss: 0.010989592001726643
Epoch 379, Loss: 0.010887756855272209
Epoch 380, Loss: 0.010786888504286557
Epoch 381, Loss: 0.010686977593044027
Epoch 382, Loss: 0.010588014857063278
Epoch 383, Loss: 0.010489991122221824
Epoch 384, Loss: 0.01039289730388071
Epoch 385, Loss: 0.010296724406016863
Epoch 386, Loss: 0.010201463520363382
Epoch 387, Loss: 0.010107105825559178
Epoch 388, Loss: 0.010013642586305936
Epoch 389, Loss: 0.009921065152533623
Epoch 390, Loss:

Epoch 770, Loss: 0.00033235605954039346
Epoch 771, Loss: 0.00032950389743238034
Epoch 772, Loss: 0.00032667659078624125
Epoch 773, Loss: 0.0003238739191439374
Epoch 774, Loss: 0.0003210956640445385
Epoch 775, Loss: 0.00031834160900540815
Epoch 776, Loss: 0.00031561153950379216
Epoch 777, Loss: 0.0003129052429586971
Epoch 778, Loss: 0.00031022250871295026
Epoch 779, Loss: 0.00030756312801490614
Epoch 780, Loss: 0.000304926894001421
Epoch 781, Loss: 0.00030231360167969746
Epoch 782, Loss: 0.0002997230479104422
Epoch 783, Loss: 0.000297155031390181
Epoch 784, Loss: 0.0002946093526346871
Epoch 785, Loss: 0.0002920858139619233
Epoch 786, Loss: 0.00028958421947534107
Epoch 787, Loss: 0.0002871043750472487
Epoch 788, Loss: 0.00028464608830260345
Epoch 789, Loss: 0.00028220916860269475
Epoch 790, Loss: 0.00027979342702920656
Epoch 791, Loss: 0.0002773986763681048
Epoch 792, Loss: 0.00027502473109385897
Epoch 793, Loss: 0.000272671407354199
Epoch 794, Loss: 0.00027033852295407475
Epoch 795, Los

# Real valued Input

In [52]:
import numpy as np

def linear(x):
    return x

def linear_derivative(x):
    return np.ones_like(x)

def mse(y_true, y_pred):
    return np.mean(np.square(y_true - y_pred))

def mse_derivative(y_true, y_pred):
    return 2 * (y_pred - y_true) / len(y_true)

# input 
X = np.array([[1.7, 2.7, 3.1, 1.9, 3.1]])

# shape of input, hidden and output layer
input_size = X.shape[1]
hidden_size = 4
output_size = input_size

# He initialization of weights
np.random.seed(0)
W1 = np.random.randn(input_size, hidden_size)
W2 = np.random.randn(hidden_size, output_size) 

# print initial weights
print(W1)
print(W2)

#  number of epochs and learning rate
epochs = 500
learning_rate = 0.001

for i in range(epochs):
    # forward pass
    hidden_layer = linear(np.dot(X, W1))
    output_layer = linear(np.dot(hidden_layer, W2))
    
    # loss 
    loss = mse(X, output_layer)
    print(f"Epoch {i}, Loss: {loss}")
    
    # backpropagation
    d_output = mse_derivative(X, output_layer) * linear_derivative(output_layer)
    d_hidden = np.dot(d_output, W2.T) * linear_derivative(hidden_layer)
    
    # update weights
    W2 -= learning_rate * np.dot(hidden_layer.T, d_output)
    W1 -= learning_rate * np.dot(X.T, d_hidden)

# output 
reconstructed = linear(np.dot(linear(np.dot(X, W1)), W2))
print()
print("W1: \n",W1)
print("W2: \n",W2)

print("\n\nActual input:", X)
print("Reconstructed input:", reconstructed)


[[ 1.76405235  0.40015721  0.97873798  2.2408932 ]
 [ 1.86755799 -0.97727788  0.95008842 -0.15135721]
 [-0.10321885  0.4105985   0.14404357  1.45427351]
 [ 0.76103773  0.12167502  0.44386323  0.33367433]
 [ 1.49407907 -0.20515826  0.3130677  -0.85409574]]
[[-2.55298982  0.6536186   0.8644362  -0.74216502  2.26975462]
 [-1.45436567  0.04575852 -0.18718385  1.53277921  1.46935877]
 [ 0.15494743  0.37816252 -0.88778575 -1.98079647 -0.34791215]
 [ 0.15634897  1.23029068  1.20237985 -0.38732682 -0.30230275]]
Epoch 0, Loss: 565.4095061935134
Epoch 1, Loss: 57.91928858195994
Epoch 2, Loss: 8.842992974313187
Epoch 3, Loss: 6.531311926437351
Epoch 4, Loss: 5.088759613024974
Epoch 5, Loss: 4.129269746829941
Epoch 6, Loss: 3.4596430728182836
Epoch 7, Loss: 2.9739117902563574
Epoch 8, Loss: 2.6099249750744153
Epoch 9, Loss: 2.329307993370487
Epoch 10, Loss: 2.1073819166417342
Epoch 11, Loss: 1.9277424427335426
Epoch 12, Loss: 1.7791840663205742
Epoch 13, Loss: 1.6538762403506262
Epoch 14, Loss: 1.

Epoch 464, Loss: 1.2258718891376512e-11
Epoch 465, Loss: 1.1576122285578603e-11
Epoch 466, Loss: 1.0931534393778812e-11
Epoch 467, Loss: 1.0322838791360606e-11
Epoch 468, Loss: 9.748036907176371e-12
Epoch 469, Loss: 9.205241451503555e-12
Epoch 470, Loss: 8.692670225728327e-12
Epoch 471, Loss: 8.208640266563465e-12
Epoch 472, Loss: 7.751562326700818e-12
Epoch 473, Loss: 7.319935647845835e-12
Epoch 474, Loss: 6.9123430384596856e-12
Epoch 475, Loss: 6.527446220311824e-12
Epoch 476, Loss: 6.1639814343932035e-12
Epoch 477, Loss: 5.820755291208657e-12
Epoch 478, Loss: 5.496640851214019e-12
Epoch 479, Loss: 5.1905739270537695e-12
Epoch 480, Loss: 4.901549587259779e-12
Epoch 481, Loss: 4.6286188565925506e-12
Epoch 482, Loss: 4.370885600886326e-12
Epoch 483, Loss: 4.127503587940467e-12
Epoch 484, Loss: 3.8976737038822345e-12
Epoch 485, Loss: 3.680641331915776e-12
Epoch 486, Loss: 3.4756938730603838e-12
Epoch 487, Loss: 3.28215840981553e-12
Epoch 488, Loss: 3.099399492779397e-12
Epoch 489, Loss: